# Service to expose the Cats vs Dogs API
apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-api
  namespace: mlops
  labels:
    app: cats-dogs-api
spec:
  type: NodePort
  selector:
    app: cats-dogs-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080

